# Workflow name
name: Deploy Vite App to GitHub Pages

on:
  # Trigger the workflow on push to the main branch or manually
  push:
    branches:
      - main
  workflow_dispatch:

# Set permissions for deploying to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Single deployment job
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 6: Upload artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

